import { chromium, expect } from '@playwright/test';
import assert from 'node:assert/strict';
import { fileURLToPath } from 'node:url';

const origin = process.env.RELAY_MOCKUP_ORIGIN || 'http://127.0.0.1:4322/relay-album-library/';
if (!['127.0.0.1', 'localhost'].includes(new URL(origin).hostname)) throw new Error('Use the isolated local mockup server.');
const browser = await chromium.launch({ channel: 'chrome' });
const page = await browser.newPage({ viewport: { width: 1440, height: 1050 }, reducedMotion: 'reduce' });
const errors = [];
const failedResponses = [];
page.on('pageerror', error => errors.push(error.message));
page.on('response', response => { if (response.status() >= 400) failedResponses.push(response.url()); });
const artifact = name => fileURLToPath(new URL(name, import.meta.url));

try {
  // Arrival must contain album metadata only, including after browser-back and responsive changes.
  await page.goto(origin);
  await expect(page.locator('.album-card')).toHaveCount(6);
  await expect(page.locator('main img, main video, .file-card')).toHaveCount(0);
  await expect(page.getByRole('button', { name: 'Open navigation' })).toBeHidden();
  await page.screenshot({ path: artifact('desktop-preview.png'), fullPage: true });
  await page.getByRole('searchbox', { name: 'Search albums' }).fill('nothing matches');
  await expect(page.getByRole('heading', { name: 'No matching albums.' })).toBeVisible();
  await page.getByRole('button', { name: 'Clear search', exact: true }).click();
  await page.getByRole('button', { name: 'List view', exact: true }).click();
  await expect(page.locator('#album-results')).toHaveClass(/list-view/);
  await page.getByRole('button', { name: 'Grid view', exact: true }).click();
  await page.getByLabel('Sort albums').selectOption('name');
  await expect(page.locator('.card-title').first()).toHaveText('Along the coast');
  await page.getByLabel('Sort albums').selectOption('recent');
  await page.getByRole('link', { name: 'Open Slow Sundays', exact: true }).click();
  await expect(page.locator('.file-card')).toHaveCount(6);
  await page.screenshot({ path: artifact('album-preview.png'), fullPage: true });
  await page.getByRole('button', { name: 'Details 2', exact: true }).click();
  await expect(page.locator('.file-card')).toHaveCount(2);
  await page.getByRole('button', { name: 'Videos', exact: true }).click();
  await expect(page.locator('.file-card')).toHaveCount(0);
  await page.getByRole('button', { name: 'Clear filters', exact: true }).click();
  await expect(page.locator('.file-card')).toHaveCount(2);
  await page.getByRole('button', { name: 'Preview A quiet corner.jpg', exact: true }).click();
  await expect(page.locator('#viewer')).toBeVisible();
  await page.keyboard.press('Escape');
  await expect(page.locator('#viewer')).not.toBeVisible();
  await page.getByRole('link', { name: 'Back to albums', exact: true }).click();
  await expect(page.locator('main img, main video, .file-card')).toHaveCount(0);
  await page.getByRole('button', { name: 'New album', exact: false }).click();
  await page.getByLabel('Album name', { exact: true }).fill('A weekend away');
  await page.getByLabel('Start with', { exact: true }).selectOption('story');
  await page.getByRole('radio', { name: 'Blue', exact: true }).check();
  await page.screenshot({ path: artifact('create-preview.png') });
  await page.getByLabel('Album name', { exact: true }).fill('Autumn <escape>');
  await page.getByRole('button', { name: 'Create album', exact: false }).click();
  await expect(page.getByRole('heading', { name: 'Autumn <escape>', exact: true })).toBeVisible();
  await expect(page.getByRole('heading', { name: 'A little space for your story.' })).toBeVisible();
  await page.getByRole('button', { name: 'Details 0', exact: true }).click();
  await page.getByRole('button', { name: 'Add files', exact: true }).click();
  await expect(page.locator('#upload-destination')).toHaveText('Personal space → Autumn <escape> → Details');
  await page.getByRole('checkbox', { name: 'Studio study.jpg Photo', exact: true }).check();
  await page.getByRole('button', { name: 'Add selected files', exact: true }).click();
  await expect(page.locator('.file-card')).toHaveCount(1);
  await expect(page.getByRole('button', { name: 'Details 1', exact: true })).toBeVisible();
  await page.getByRole('link', { name: 'Unorganised 2', exact: true }).click();
  await expect(page.locator('.file-card')).toHaveCount(2);
  await page.getByLabel('Workspace', { exact: true }).selectOption('shared');
  await expect(page.locator('.album-card')).toHaveCount(1);
  await expect(page.getByRole('link', { name: 'Open Slow Sundays', exact: true })).toHaveCount(0);
  await page.getByLabel('Workspace', { exact: true }).selectOption('personal');
  await expect(page.locator('.album-card')).toHaveCount(7);
  await page.reload();
  await expect(page.locator('.album-card')).toHaveCount(6);
  for (const width of [320, 390, 768, 1024, 1440]) {
    await page.setViewportSize({ width, height: 900 });
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true, `Overflow at ${width}`);
    await expect(page.locator('main img, main video, .file-card')).toHaveCount(0);
  }
  await page.setViewportSize({ width: 390, height: 844 });
  await page.screenshot({ path: artifact('mobile-preview.png'), fullPage: true });
  await page.getByRole('button', { name: 'Open navigation', exact: true }).click();
  await expect(page.getByLabel('Workspace', { exact: true })).toBeVisible();
  await page.keyboard.press('Escape');
  await expect(page.getByRole('button', { name: 'Open navigation' })).toBeFocused();
  await page.getByRole('link', { name: 'Open Slow Sundays', exact: true }).click();
  await expect(page.locator('.file-card')).toHaveCount(6);
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true, 'Mobile detail overflow');
  await page.screenshot({ path: artifact('mobile-album-preview.png'), fullPage: true });
  await page.getByRole('button', { name: 'Add files', exact: true }).click();
  await page.locator('#local-files').setInputFiles(artifact('../relay-app-refresh/assets/chair.jpg'));
  await expect(page.locator('.file-card')).toHaveCount(7);
  await page.getByRole('button', { name: 'Preview chair.jpg', exact: true }).click();
  await expect(page.locator('#viewer img')).toBeVisible();
  await page.keyboard.press('Escape');
  await page.goBack();
  await expect(page.locator('main img, main video, .file-card')).toHaveCount(0);
  assert.deepEqual(errors, []);
  assert.deepEqual(failedResponses, []);
  console.log('PASS: album-only arrival, search/sort/views, scoped sections and filters, preview/Escape, safe text creation, destination-specific filing, workspace separation, local photo preview, browser back, mobile drawer, 320–1440px overflow, no page errors or failed responses.');
} finally {
  await browser.close();
}
