// Removal candidate: prior manually maintained bindings, superseded by Wrangler generation.
/*
declare namespace Cloudflare {
  interface Env {
    DB?: D1Database;
    BUCKET?: R2Bucket;
  }
}

*/
/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=dist/server/wrangler.direct.json --include-runtime=false .sites-runtime/worker-bindings.d.ts` (hash: 58cc65c5a9a51ad493c32e09df8e02f7)
interface __BaseEnv_Env {
	BUCKET: R2Bucket;
	DB: D1Database;
	API_RATE_LIMIT: RateLimit;
	PAIR_RATE_LIMIT: RateLimit;
	DEVICE_RATE_LIMIT: RateLimit;
	WRITE_RATE_LIMIT: RateLimit;
	R2_ACCOUNT_ID: "5afd1facc45c9ddd86114155b09fc2e2";
	R2_BUCKET_NAME: "relay-media-originals";
	ALLOW_SPACE_CREATION: "false";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./dist/server/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "R2_ACCOUNT_ID" | "R2_BUCKET_NAME" | "ALLOW_SPACE_CREATION">> {}
}
