/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=deploy/wrangler.identity-monitor.jsonc --include-runtime=false --strict-vars=false --env-interface=IdentityMonitorEnv deploy/identity-monitor-env.d.ts` (hash: f207b625eb4c205f1d4888ad48a2e7b2)
interface __BaseEnv_IdentityMonitorEnv {
	MONITOR_ENABLED: string;
	AUTH0_MONITOR_CLIENT_ID: string;
	AUTH0_MONITOR_CLIENT_SECRET: string;
	CLOUDFLARE_D1_READ_TOKEN: string;
	RELAY_MONITOR_SECRET: string;
	RELAY: Fetcher /* relay-media-exchange */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./identity-monitor-worker");
	}
	interface Env extends __BaseEnv_IdentityMonitorEnv {}
}
interface IdentityMonitorEnv extends __BaseEnv_IdentityMonitorEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "MONITOR_ENABLED" | "AUTH0_MONITOR_CLIENT_ID" | "AUTH0_MONITOR_CLIENT_SECRET" | "CLOUDFLARE_D1_READ_TOKEN" | "RELAY_MONITOR_SECRET">> {}
}
